version: '3.8'

services:
  graph_index:
    image: nyusafonov/graph_index:latest
    container_name: graph-index
    environment:
      GRPC_PORT: 8083
      GRAPH_DIRECTORY: /opt/graph
    networks:
      - orp-network
    volumes:
      - ./src/main/resources/odintsovo/odintsovo-graphml.xml:/opt/graph/odintsovo.xml
    ports:
      - "8083:8083"
networks:
  orp-network:
    name: orp-network
    driver: bridge